---
# LEEROOOOOOOOOOOOY JENKINS
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: leeroy_jenkins
    privileged: true
    user: root
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.change.me`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=myresolver"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: leeroy_jenkins_agent
    privileged: true
    user: root
    networks:
      - internal
    #environment:
    #  - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}

networks:
  proxy:
    name: proxy
  internal:
    driver: bridge